// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrSodF7zXLKPPOiDjqOiwm2taJoFRzluo',
    appId: '1:979019672254:web:23956765e797ca55894cef',
    messagingSenderId: '979019672254',
    projectId: 'signinfirebase-a6c72',
    authDomain: 'signinfirebase-a6c72.firebaseapp.com',
    storageBucket: 'signinfirebase-a6c72.appspot.com',
    measurementId: 'G-CL6979P9XY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL8I6jNsdDdz2ef22rxWRRalAO02rCmfg',
    appId: '1:979019672254:android:5e528d56a68db7d0894cef',
    messagingSenderId: '979019672254',
    projectId: 'signinfirebase-a6c72',
    storageBucket: 'signinfirebase-a6c72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTihTrbhppUErNEV7S58u2S85OSM5pk4g',
    appId: '1:979019672254:ios:fcbf18e744f30de3894cef',
    messagingSenderId: '979019672254',
    projectId: 'signinfirebase-a6c72',
    storageBucket: 'signinfirebase-a6c72.appspot.com',
    iosBundleId: 'com.example.drivinghubWelcomeLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTihTrbhppUErNEV7S58u2S85OSM5pk4g',
    appId: '1:979019672254:ios:fcbf18e744f30de3894cef',
    messagingSenderId: '979019672254',
    projectId: 'signinfirebase-a6c72',
    storageBucket: 'signinfirebase-a6c72.appspot.com',
    iosBundleId: 'com.example.drivinghubWelcomeLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrSodF7zXLKPPOiDjqOiwm2taJoFRzluo',
    appId: '1:979019672254:web:d8b06df5da1b64c1894cef',
    messagingSenderId: '979019672254',
    projectId: 'signinfirebase-a6c72',
    authDomain: 'signinfirebase-a6c72.firebaseapp.com',
    storageBucket: 'signinfirebase-a6c72.appspot.com',
    measurementId: 'G-G6SP6JTMBL',
  );
}
